lcd_char_{{index}}[0]=B{{row1}};
lcd_char_{{index}}[1]=B{{row2}};
lcd_char_{{index}}[2]=B{{row3}};
lcd_char_{{index}}[3]=B{{row4}};
lcd_char_{{index}}[4]=B{{row5}};
lcd_char_{{index}}[5]=B{{row6}};
lcd_char_{{index}}[6]=B{{row7}};
lcd_char_{{index}}[7]=B{{row8}};
lcd.createChar({{index}},lcd_char_{{index}});